from __future__ import annotations

from typing import Dict, List, Protocol

from .models import OrderAction, FillEvent, StrategyContext

class ReactiveStrategy(Protocol):
    symbols: List[str]

    def on_tick(self, ctx: StrategyContext) -> List[OrderAction]: ...
    def on_fill(self, fill: FillEvent) -> None: ...

    def register_order(self, order_id: str, action: OrderAction) -> None: ...
    def pending_orders(self) -> Dict[str, OrderAction]: ...
    def clear_order(self, order_id: str) -> None: ...

    def snapshot_line(self, prices: dict) -> str: ...
    def persist(self) -> None: ...
    def is_paused(self) -> bool: ...
    def get_cash(self) -> float: ...
